
module.exports ={
    Butacas:[
        {
            id:1,
            columna:'A1',
            fila:'A',
            disponible:true
        },
        {
            id:2,
            columna:'A2',
            fila:'A',
            disponible:false
        },
        {
            id:3,
            columna:'A3',
            fila:'A',
            disponible:true
        },
        {
            id:4,
            columna:'A4',
            fila:'A',
            disponible:false
        },
        {
            id:5,
            columna:'A5',
            fila:'A',
            disponible:true
        },
        {
            id:6,
            columna:'A6',
            fila:'A',
            disponible:true
        },
        {
            id:7,
            columna:'A7',
            fila:'A',
            disponible:true
        },
        {
            id:8,
            columna:'A8',
            fila:'A',
            disponible:true
        },
        {
            id:9,
            columna:'A9',
            fila:'A',
            disponible:true
        },
        {
            id:10,
            columna:'A10',
            fila:'A',
            disponible:true
        },
        {
            id:11,
            columna:'A11',
            fila:'A',
            disponible:true
        },
        {
            id:12,
            columna:'A12',
            fila:'A',
            disponible:true
        },
        {
            id:13,
            columna:'A13',
            fila:'A',
            disponible:true
        },
        {
            id:14,
            columna:'A14',
            fila:'A',
            disponible:true
        },
        {
            id:1,
            columna:'B1',
            fila:'B',
            disponible:true
        },
        {
            id:2,
            columna:'B2',
            fila:'B',
            disponible:true
        },
        {
            id:3,
            columna:'B3',
            fila:'B',
            disponible:true
        },
        {   
            id:4,
            columna:'B4',
            fila:'B',
            disponible:true
        },
        {
            id:5,
            columna:'B5',
            fila:'B',
            disponible:true
        },
        {
            id:6,
            columna:'B6',
            fila:'B',
            disponible:true
        },
        {
            id:7,
            columna:'B7',
            fila:'B',
            disponible:true
        },
        {
            id:8,
            columna:'B8',
            fila:'B',
            disponible:true
        },
        {
            id:9,
            columna:'B9',
            fila:'B',
            disponible:true
        },
        {
            id:10,
            columna:'B10',
            fila:'B',
            disponible:true
        },
        {
            id:11,
            columna:'B11',
            fila:'B',
            disponible:true
        },
        {
            id:12,
            columna:'B12',
            fila:'B',
            disponible:true
        },
        {
            id:13,
            columna:'B13',
            fila:'B',
            disponible:true
        },
        {
            id:14,
            columna:'B14',
            fila:'B',
            disponible:true
        },
        {
            id:1,
            columna:'C1',
            fila:'C',
            disponible:true
        },
        {
            id:2,
            columna:'C2',
            fila:'C',
            disponible:true
        },
        {
            id:3,
            columna:'C3',
            fila:'C',
            disponible:true
        },
        {
            id:4,
            columna:'C4',
            fila:'C',
            disponible:true
        },
        {
            id:5,
            columna:'C5',
            fila:'C',
            disponible:true
        },
        {
            id:6,
            columna:'C6',
            fila:'C',
            disponible:true
        },
        {
            id:7,
            columna:'C7',
            fila:'C',
            disponible:true
        },
        {
            id:8,
            columna:'C8',
            fila:'C',
            disponible:true
        },
        {
            id:9,
            columna:'C9',
            fila:'C',
            disponible:true
        },
        {
            id:10, 
            columna:'C10',
            fila:'C',
            disponible:true
        },
        {   id:11,
            columna:'C11',
            fila:'C',
            disponible:true
        },
        {   
            id:12,
            columna:'C12',
            fila:'C',
            disponible:true
        },
        {
            id:13,
            columna:'C13',
            fila:'C',
            disponible:true
        },
        {   
            id:14,
            columna:'C14',
            fila:'C',
            disponible:true
        },
        {
            id:1,
            columna:'D1',
            fila:'D',
            disponible:true
        },
        {
            id:2,
            columna:'D2',
            fila:'D',
            disponible:true
        },
        {
            id:3,
            columna:'D3',
            fila:'D',
            disponible:true
        },
        {
            id:4,
            columna:'D4',
            fila:'D',
            disponible:true
        },
        {
            id:5,
            columna:'D5',
            fila:'D',
            disponible:true
        },
        {
            id:6,
            columna:'D6',
            fila:'D',
            disponible:true
        },
        {
            id:7,
            columna:'D7',
            fila:'D',
            disponible:true
        },
        {
            id:8,
            columna:'D8',
            fila:'D',
            disponible:true
        },
        {
            id:9,
            columna:'D9',
            fila:'D',
            disponible:true
        },
        {
            id:10,
            columna:'D10',
            fila:'D',
            disponible:true
        },
        {
            id:11,
            columna:'D11',
            fila:'D',
            disponible:true
        },
        {
            id:12,
            columna:'D12',
            fila:'D',
            disponible:true
        },
        {
            id:13,
            columna:'D13',
            fila:'D',
            disponible:true
        },
        {
            id:14,
            columna:'D14',
            fila:'D',
            disponible:true
        },
        {
            id:1,
            columna:'E1',
            fila:'E',
            disponible:true
        },
        {
            id:2,
            columna:'E2',
            fila:'E',
            disponible:true
        },
        {
            id:3,
            columna:'E3',
            fila:'E',
            disponible:true
        },
        {
            id:4,
            columna:'E4',
            fila:'E',
            disponible:true
        },
        {
            id:5,
            columna:'E5',
            fila:'E',
            disponible:true
        },
        {
            id:6,
            columna:'E6',
            fila:'E',
            disponible:true
        },
        {
            id:7,
            columna:'E7',
            fila:'E',
            disponible:true
        },
        {
            id:8,
            columna:'E8',
            fila:'E',
            disponible:true
        },
        {
            id:9,
            columna:'E9',
            fila:'E',
            disponible:true
        },
        {
            id:10,
            columna:'E10',
            fila:'E',
            disponible:true
        },
        {
            id:11,
            columna:'E11',
            fila:'E',
            disponible:true
        },
        {
            id:12,
            columna:'E12',
            fila:'E',
            disponible:true
        },
        {
            id:13,
            columna:'E13',
            fila:'E',
            disponible:true
        },
        {
            id:14,
            columna:'E14',
            fila:'E',
            disponible:true
        },
        {
            id:1,
            columna:'F1',
            fila:'F',
            disponible:true
        },
        {
            id:2,
            columna:'F2',
            fila:'F',
            disponible:true
        },
        {
            id:3,
            columna:'F3',
            fila:'F',
            disponible:true
        },
        {
            id:4,
            columna:'F4',
            fila:'F',
            disponible:true
        },
        {
            id:5,
            columna:'F5',
            fila:'F',
            disponible:true
        },
        {
            id:6,
            columna:'F6',
            fila:'F',
            disponible:true
        },
        {
            id:7,
            columna:'F7',
            fila:'F',
            disponible:true
        },
        {
            id:8,
            columna:'F8',
            fila:'F',
            disponible:true
        },
        {
            id:9,
            columna:'F9',
            fila:'F',
            disponible:true
        },
        {
            id:10,
            columna:'F10',
            fila:'F',
            disponible:true
        },
        {
            id:11,
            columna:'F11',
            fila:'F',
            disponible:true
        },
        {
            id:12,
            columna:'F12',
            fila:'F',
            disponible:true
        },
        {
            id:13,
            columna:'F13',
            fila:'F',
            disponible:true
        },
        {
            id:14,
            columna:'F14',
            fila:'F',
            disponible:true
        },
        {
            id:1,
            columna:'G1',
            fila:'G',
            disponible:true
        },
        {
            id:2,
            columna:'G2',
            fila:'G',
            disponible:true
        },
        {
            id:3,
            columna:'G3',
            fila:'G',
            disponible:true
        },
        {
            id:4,
            columna:'G4',
            fila:'G',
            disponible:true
        },
        {
            id:5,
            columna:'G5',
            fila:'G',
            disponible:true
        },
        {
            id:6,
            columna:'G6',
            fila:'G',
            disponible:true
        },
        {
            id:7,
            columna:'G7',
            fila:'G',
            disponible:true
        },
        {
            id:8,
            columna:'G8',
            fila:'G',
            disponible:true
        },
        {
            id:9,
            columna:'G9',
            fila:'G',
            disponible:true
        },
        {
            id:10,
            columna:'G10',
            fila:'G',
            disponible:true
        },
        {
            id:11,
            columna:'G11',
            fila:'G',
            disponible:true
        },
        {
            id:12,
            columna:'G12',
            fila:'G',
            disponible:true
        },
        {
            id:13,
            columna:'G13',
            fila:'G',
            disponible:true
        },
        {
            id:14,
            columna:'G14',
            fila:'G',
            disponible:true
        },
        {
            id:1,
            columna:'H1',
            fila:'H',
            disponible:true
        },
        {
            id:2,
            columna:'H2',
            fila:'H',
            disponible:true
        },
        {
            id:3,
            columna:'H3',
            fila:'H',
            disponible:true
        },
        {
            id:4,
            columna:'H4',
            fila:'H',
            disponible:true
        },
        {
            id:5,
            columna:'H5',
            fila:'H',
            disponible:true
        },
        {
            id:6,
            columna:'H6',
            fila:'H',
            disponible:true
        },
        {
            id:7,
            columna:'H7',
            fila:'H',
            disponible:true
        },
        {
            id:8,
            columna:'H8',
            fila:'H',
            disponible:true
        },
        {
            id:9,
            columna:'H9',
            fila:'H',
            disponible:true
        },
        {
            id:10,
            columna:'H10',
            fila:'H',
            disponible:true
        },
        {
            id:11,
            columna:'H11',
            fila:'H',
            disponible:true
        },
        {
            id:12,
            columna:'H12',
            fila:'H',
            disponible:true
        },
        {
            id:13,
            columna:'H13',
            fila:'H',
            disponible:true
        },
        {
            id:14,
            columna:'H14',
            fila:'H',
            disponible:true
        }
    ]
   
}

module.exports.obtenerButacas = function () {
    return this.Butacas; 
  };